_wandb:
    value:
        cli_version: 0.23.1
        e:
            j64i88zjo4lyp74gpepjiqlrslqpv138:
                codePath: src/TrainUnet.py
                codePathLocal: src/TrainUnet.py
                cpu_count: 24
                cpu_count_logical: 24
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "76817485824"
                        used: "7294750720"
                email: lucpares01@gmail.com
                executable: /zhome/98/d/202490/Documents/Thesis/clim-dif/bin/python
                git:
                    commit: 298377bb901db99d84547331e8f1df16b97955fb
                    remote: git@github.com:LPares01/HeatwavesDiffuse-DK
                gpu: Tesla V100-PCIE-32GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "34359738368"
                      name: Tesla V100-PCIE-32GB
                      uuid: GPU-08988bda-1ff6-da3b-a16e-040e7bd619e3
                host: n-62-20-16
                memory:
                    total: "404874924032"
                os: Linux-6.1.161-1.el9.elrepo.x86_64-x86_64-with-glibc2.34
                program: /zhome/98/d/202490/Documents/Thesis/ClimateDiffuse/src/TrainUnet.py
                python: CPython 3.9.25
                root: /zhome/98/d/202490/Documents/Thesis/ClimateDiffuse
                startedAt: "2026-02-11T13:40:29.715757Z"
                writerId: j64i88zjo4lyp74gpepjiqlrslqpv138
        m: []
        python_version: 3.9.25
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 2
                - 16
            "4": 3.9.25
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
accum:
    value: 8
architecture:
    value: unet
batch_size:
    value: 8
dataset:
    value: full
epochs:
    value: 90
learning_rate:
    value: 0.0001
load_checkpoint:
    value: true
loss_fn:
    value: MSE
percentile:
    value: 95
run_ID:
    value: "03"
save_checkpoint:
    value: true
sea_mask:
    value: false
