_wandb:
    value:
        cli_version: 0.23.1
        e:
            e3zpu7jqyuvz8r6ac4hp3op2r8h5je7d:
                codePath: examples/train_minimal.py
                codePathLocal: train_minimal.py
                cpu_count: 32
                cpu_count_logical: 32
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "76817485824"
                        used: "9218457600"
                email: lucpares01@gmail.com
                executable: /zhome/98/d/202490/Documents/Thesis/clim-dif/bin/python
                git:
                    commit: 298377bb901db99d84547331e8f1df16b97955fb
                    remote: git@github.com:LPares01/HeatwavesDiffuse-DK
                gpu: Tesla V100-SXM2-32GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "34359738368"
                      name: Tesla V100-SXM2-32GB
                      uuid: GPU-716a9097-dd3b-c568-7482-6fb712b41563
                host: n-62-20-10
                memory:
                    total: "404837019648"
                os: Linux-6.1.159-1.el9.elrepo.x86_64-x86_64-with-glibc2.34
                program: /zhome/98/d/202490/Documents/Thesis/ClimateDiffuse/examples/train_minimal.py
                python: CPython 3.9.23
                root: /zhome/98/d/202490/Documents/Thesis/ClimateDiffuse/examples
                startedAt: "2025-12-18T11:25:14.195651Z"
                writerId: e3zpu7jqyuvz8r6ac4hp3op2r8h5je7d
        m: []
        python_version: 3.9.23
        t:
            "1":
                - 1
                - 2
                - 3
                - 41
            "2":
                - 1
                - 2
                - 3
                - 41
            "3":
                - 2
                - 16
            "4": 3.9.23
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
accum:
    value: 16
architecture:
    value: U-Net
batch_size:
    value: 8
dataset:
    value: minimal
epochs:
    value: 10
learning_rate:
    value: 0.0001
