_wandb:
    value:
        cli_version: 0.23.1
        e:
            4jrpdl1cao6cw3zev4ookyo3p4cnd0o2:
                codePath: src/TrainUnet.py
                codePathLocal: src/TrainUnet.py
                cpu_count: 32
                cpu_count_logical: 32
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "76817485824"
                        used: "8005988352"
                email: lucpares01@gmail.com
                executable: /zhome/98/d/202490/Documents/Thesis/clim-dif/bin/python
                git:
                    commit: 298377bb901db99d84547331e8f1df16b97955fb
                    remote: git@github.com:LPares01/HeatwavesDiffuse-DK
                gpu: Tesla V100-SXM2-32GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "34359738368"
                      name: Tesla V100-SXM2-32GB
                      uuid: GPU-9f1fde6c-6e6a-d5e2-c8bb-4afb14d3789f
                host: n-62-20-11
                memory:
                    total: "404837015552"
                os: Linux-6.1.161-1.el9.elrepo.x86_64-x86_64-with-glibc2.34
                program: /zhome/98/d/202490/Documents/Thesis/ClimateDiffuse/src/TrainUnet.py
                python: CPython 3.9.25
                root: /zhome/98/d/202490/Documents/Thesis/ClimateDiffuse
                startedAt: "2026-02-09T09:00:21.723246Z"
                writerId: 4jrpdl1cao6cw3zev4ookyo3p4cnd0o2
        m: []
        python_version: 3.9.25
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 2
                - 16
            "4": 3.9.25
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
accum:
    value: 8
architecture:
    value: unet
batch_size:
    value: 8
dataset:
    value: full
epochs:
    value: 180
learning_rate:
    value: 0.0001
load_checkpoint:
    value: true
loss_fn:
    value: MSE
percentile:
    value: 95
save_checkpoint:
    value: false
sea_mask:
    value: true
